version: '3.7'

services:
  urbanice_node:
    container_name: urbanice_node
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    restart: always
    ports:
      - "5319:80"
    volumes:
      - .:/usr/src/app:cached
      - ./.env.local:/usr/src/app/.env:cached
      - ./docker/oauth/dev/oauth-public.key:/usr/src/app/storage/oauth-public.key:cached
      - ./docker/oauth/dev/oauth-public.key:/usr/src/app/storage/oauth-public.test.key:cached
      - /usr/src/app/node_modules
    environment:
      APP_ENV: local
      NODE_ENV: local
      HTTPS_METHOD: noredirect # support both http and https
    networks:
      network-urbanice:
  node-mariadb:
    image: mariadb:10.4.3-bionic
    container_name: node-mariadb
    restart: always
    ports:
      - 5080:3306
    volumes:
      - /var/lib/mysql
    networks:
      network-urbanice:
        aliases:
          - db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
  node-pma:
    image: phpmyadmin/phpmyadmin:5
    container_name: node-pma
    depends_on:
      - node-mariadb
    restart: always
    ports:
      - 5880:80
    networks:
      network-urbanice:
        aliases:
          - phpmyadmin
    environment:
      PMA_HOST: node-mariadb
      PMA_PORT: 3306
networks:
  network-urbanice:
    external: false
    name: network-urbanice
